# Generated by Django 2.2 on 2024-02-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_database', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobby_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vectors%2Fdefault-vectors&psig=AOvVaw1HZTNr33G9NPvDy6ghkHyy&ust=1708383510425000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCJCMm9T-tYQDFQAAAAAdAAAAABAE', max_length=800),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vectors%2Fdefault-vectors&psig=AOvVaw1HZTNr33G9NPvDy6ghkHyy&ust=1708383510425000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCJCMm9T-tYQDFQAAAAAdAAAAABAE', max_length=800),
        ),
    ]
