# Generated by Django 2.2 on 2024-02-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_database', '0003_auto_20240218_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='hobby_image',
            field=models.CharField(default='https://www.shutterstock.com/image-vector/default-ui-image-placeholder-wireframes-260nw-1037719192.jpg', max_length=800),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_image',
            field=models.CharField(default='https://www.shutterstock.com/image-vector/default-ui-image-placeholder-wireframes-260nw-1037719192.jpg', max_length=800),
        ),
    ]
